export const generalReportTableRows = [
  {
    srNo: '',
    name: '',
    amount: '',
    srNoAgain: 1,
    nameAgain: 'dummy_1',
    amountAgain: 144500,
  },
  {
    srNo: '',
    name: '',
    amount: '',
    srNoAgain: 2,
    nameAgain: 'rahul',
    amountAgain: 714500,
  },
  {
    srNo: '',
    name: '',
    amount: '',
    srNoAgain: 3,
    nameAgain: 'pankaj',
    amountAgain: 7584500,
  },
  {
    srNo: '',
    name: '',
    amount: '',
    srNoAgain: 4,
    nameAgain: 'mukesh_0578',
    amountAgain: 568500,
  },
  {
    srNo: '',
    name: '',
    amount: '',
    srNoAgain: 5,
    nameAgain: 'kunal_7457',
    amountAgain: 144782,
  },
  {
    srNo: '',
    name: '',
    amount: '',
    srNoAgain: 6,
    nameAgain: 'john_1423',
    amountAgain: 758500,
  },
];
