export const accountTableMapping = [
  {
    displayName: 'User Name',
    type: 'template',
    fieldName: 'username',
    width: 120,
    sortable: false,
  },
  {
    displayName: 'Credit Reference',
    type: 'text',
    fieldName: 'creditReferance',
    width: 150,
    sortable: true,
  },
  {
    displayName: 'Master Balance',
    type: 'text',
    fieldName: 'balance',
    width: 140,
    sortable: true,
  },
  {
    displayName: 'Client(P/L)',
    type: 'text',
    fieldName: 'client',
    width: 100,
    sortable: true,
  },
  {
    displayName: 'Exposure',
    type: 'text',
    fieldName: 'exposure',
    width: 100,
    sortable: true,
  },
  {
    displayName: 'Available Balance',
    type: 'text',
    fieldName: 'availableBalance',
    width: 145,
    sortable: true,
  },
  {
    displayName: 'U St',
    type: 'class',
    iconClass: [{ value: 'true', class: 'fa fa-check-circle' }],
    fieldName: 'ust',
    width: 50,
    sortable: false,
  },
  {
    displayName: 'B St',
    type: 'class',
    iconClass: [{ value: 'true', class: 'fa fa-check-circle' }],
    fieldName: 'bst',
    width: 50,
    sortable: false,
  },
  {
    displayName: 'Exposure Limit',
    type: 'text',
    fieldName: 'exposureLimit',
    width: 130,
    sortable: true,
  },
  {
    displayName: 'Default',
    type: 'text',
    fieldName: 'default',
    width: 80,
    sortable: true,
  },
  {
    displayName: 'Account Type',
    type: 'text',
    fieldName: 'accountType',
    width: 120,
    sortable: true,
  },
  {
    displayName: '- Commission',
    type: 'text',
    fieldName: 'commission',
    width: 130,
    sortable: true,
  },
  {
    displayName: 'Actions',
    type: 'template',
    fieldName: 'actions',
    width: 180,
    sortable: false,
  },
];
